### ISSUE TITLE
(A question) About deploy to Netlify

### ISSUE THREAD

**Issue by dejalavidavolar** [e-hat/webring-netlify#1]
Hi! I hope you are well. I m trying to make a web-ring and I just see this and I really like it. Is there a possibility to update dependences? Because I tried to deploy to Netlify, but it doesn't works. Please, It would be very nice!

Regards!

(Sorry about my english)

**Comment by efthatfield** [comment]
Hey, I think you should probably follow the latest with this guide: https://mxb.dev/blog/webring-kit/ . Tbh I haven't looked at this for almost a year so I sorta forget how it works, either way this repo is really just a fork of the example one found in the guide and maybe that one is updated.
